#!/bin/sh

if [ -d /sys/firmware/efi -a -d "/boot/efi/EFI/openmandriva" ]; then
    su --login root -c "/usr/sbin/grub2-mkconfig -o /boot/efi/EFI/openmandriva/grub.cfg ; /usr/sbin/grub2-install --compress=xz --force --recheck --grub-setup=/bin/true"
else
    su --login root -c "/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg"
fi
